version: '3.8'

services:
  scrapy:
    build: .
    container_name: scrapy_container
    volumes:
      - .:/app
    command: scrapy crawl champions_league
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_DATABASE: champions

  mysql:
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: champions
    ports:
      - "3306:3306"
